# for run index.html
version: '3.5'

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    volumes:
      - .:/usr/local/apache2/htdocs
    container_name: index-page
